# Generated by Django 5.0.3 on 2024-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripeCustomerId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
