# Generated by Django 5.0.3 on 2024-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0002_alter_stripecustomer_stripecustomerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
