# Generated by Django 5.0.3 on 2024-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0003_alter_stripecustomer_stripesubscriptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
