# Generated by Django 5.0.3 on 2024-04-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0007_leccionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccionvideo',
            name='url_video',
            field=models.URLField(max_length=100),
        ),
    ]
