# Generated by Django 5.0.3 on 2024-05-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0011_remove_leccionvideo_url_video_leccionvideo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_capitulo', models.FileField(blank=True, upload_to='presentacion_del_capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion_name', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='lecciones')),
                ('video_url', models.URLField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_store.capitulo')),
            ],
        ),
    ]
