# Generated by Django 5.0.3 on 2024-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0012_capitulo_leccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='content',
            field=models.FileField(blank=True, upload_to='lecciones'),
        ),
    ]
