# Generated by Django 5.0.3 on 2024-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0013_alter_leccion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
