# Generated by Django 5.0.3 on 2024-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0014_alter_leccion_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='video_url',
            field=models.CharField(max_length=1000),
        ),
    ]
