# Generated by Django 5.0.3 on 2024-05-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0015_alter_leccion_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitulo',
            old_name='title',
            new_name='name_category',
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.FileField(blank=True, upload_to='lecciones')),
                ('url', models.CharField(max_length=1000)),
                ('capitulo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='video_store.capitulo')),
            ],
        ),
        migrations.DeleteModel(
            name='Leccion',
        ),
    ]
