# Generated by Django 5.0.3 on 2024-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store', '0016_rename_title_capitulo_name_category_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='video_capitulo',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='videos',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
