"""
Django settings for academia_gabriel project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



MAILGUN_API_KEY=config('MAILGUN_API_KEY')
MAILGUN_SENDER_DOMAIN=config('MAILGUN_SENDER_DOMAIN')
EMAIL_BACKEND="anymail.backends.mailgun.EmailBackend"


ANYMAIL={


'MAILGUN_API_KEY':MAILGUN_API_KEY,
'MAILGUN_SENDER_DOMAIN':MAILGUN_SENDER_DOMAIN




}
DEFAULT_FROM_EMAIL = f'noreply@{MAILGUN_SENDER_DOMAIN}'


STRIPE_PUBLIC_KEY = "pk_test_51P47uBDAqBiVLFauZOPG5Md1n60bTqRkOkMsmrR0mIUTXffkqBvZZfGlWIbnNALBa67Pw0zkFurfyIqlUvRv6mDZ00F6KzNQnU"
STRIPE_SECRET_KEY = "sk_test_51P47uBDAqBiVLFausPsLNWIyub6pDauqaprsxnNKXCegwExJe7AJw83F6OnOLvJxVE2PYi3XazAH8FTC7L2oyasc00kGmSrGaW"
STRIPE_WEBHOOK_SECRET = "whsec_NysioGhivaKLx7j9AatAlcprgnywEmso"


 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bk@86!nwh&6#8xgm2)o9gs^z3tx+zr%+*%&yalaj-dpv8b7_yl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'video_store',
    'tailwind',
    'theme',
    'fontawesomefree',
    'anymail',
    'corsheaders',
    'rest_framework'
]

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS =[
    '127.0.0.1',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'academia_gabriel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academia_gabriel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS =[
    BASE_DIR/'video_store/static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"